os: osx
osx_image: xcode14  

language: node_js
node_js:
  - "18"  

before_install:
  - npm install -g npm@7  
  - npm -v  
  - brew update  
  - brew install node  
  - brew install watchman  
  - gem install cocoapods -v '1.10.0'  

cache:
  directories:
    - node_modules  

install:
  - npm install -g react-native-cli 
  - npm install  
  - (cd ios && pod install)  

before_script:
  - xcrun simctl list  

script:
  - xcrun simctl boot "iPhone 11"  
  - sleep 40 
  - react-native run-ios --simulator="iPhone 11" --no-packager  