os: osx
osx_image: xcode12.5  
language: node_js
node_js:
  - "18"  

before_install:
  - npm install -g npm@7 
  - npm -v  

cache:
  directories:
    - node_modules

install:
  - npm install -g react-native-cli
  - npm install

before_script:
  - xcrun simctl list
  

script:
  - xcrun simctl boot "iPhone 11" 
  - sleep 10 
  - react-native run-ios --simulator="iPhone 11" --no-packager
