os: osx
osx_image: xcode12.5  
language: node_js
node_js:
  - "16"  

before_install:
  - npm install -g npm@7 
  - npm -v  

cache:
  directories:
    - node_modules

install:
  - npm install -g react-native-cli
  - npm install

script:
  - react-native run-ios --configuration=Release --simulator="iPhone 11"

