os: osx
osx_image: xcode13.4

language: node_js
node_js:
  - "18"  

before_install:
  - ruby --version
  - npm install -g npm@7  
  - npm -v  

   

cache:
  directories:
    - node_modules  

install:
  - npm install -g react-native-cli 
  - npm install  
  - (cd ios && pod install)  

before_script:
  - xcrun simctl list  

script:
  - xcrun simctl boot "iPhone 11"  
