os: osx
osx_image: xcode12.5  
language: node_js

before_install:
  - brew update
  - brew install --cask xcode

cache:
  directories:
    - node_modules

install:
  - npm install -g react-native-cli
  - npm install

script:
  - react-native run-ios --configuration=Release --simulator="iPhone 11"

